import { baseProps, makeArrayProp, makeBooleanProp, makeNumberProp, makeNumericProp, makeStringProp } from '../common/props'
import type { FormItemRule } from '../wd-form/types'

export const inputProps = {
  ...baseProps,
  customInputClass: makeStringProp(''),
  customLabelClass: makeStringProp(''),
  // 原生属性
  placeholder: String,
  placeholderStyle: String,
  placeholderClass: makeStringProp(''),
  cursorSpacing: makeNumberProp(0),
  cursor: makeNumberProp(-1),
  selectionStart: makeNumberProp(-1),
  selectionEnd: makeNumberProp(-1),
  adjustPosition: makeBooleanProp(true),
  holdKeyboard: makeBooleanProp(false),
  confirmType: makeStringProp('done'),
  confirmHold: makeBooleanProp(false),
  focus: makeBooleanProp(false),
  type: makeStringProp('text'),
  maxlength: makeNumberProp(-1),
  disabled: makeBooleanProp(false),
  alwaysEmbed: makeBooleanProp(false),
  // 原生属性结束
  alignRight: makeBooleanProp(false),
  modelValue: makeNumericProp(''),
  showPassword: makeBooleanProp(false),
  clearable: makeBooleanProp(false),
  readonly: makeBooleanProp(false),
  useSuffixSlot: makeBooleanProp(false),
  usePrefixSlot: makeBooleanProp(false),
  prefixIcon: String,
  suffixIcon: String,
  showWordLimit: makeBooleanProp(false),
  label: String,
  labelWidth: makeStringProp('33%'),
  useLabelSlot: makeBooleanProp(false),
  size: String,
  error: makeBooleanProp(false),
  center: makeBooleanProp(false),
  noBorder: makeBooleanProp(false),
  required: makeBooleanProp(false),
  prop: String,
  rules: makeArrayProp<FormItemRule>()
}
