name: Upload Docs to OSS

on:
  push:
    branches:
      - release

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - uses: pnpm/action-setup@v4
        name: Install pnpm
 
      - name: Install Dependencies and Build Docs
        run: |
          pnpm install
          pnpm build:docs

      - name: Setup Aliyun OSS
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY }}
          access-key-secret: ${{ secrets.OSS_SECRET }}

      - name: Upload Docs to OSS
        run: |
          ossutil cp -r -f ./docs/.vitepress/dist oss://wot-design-uni